name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Localization (for GlobalMaterialLocalizations only)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  url_launcher: ^6.2.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lints and
  # activating additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  flutter_lints: ^6.0.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  provider: ^6.1.2
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  intl: ^0.19.0
  uuid: ^4.4.0
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
