// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUt0D33bGHJXbeauXkmGaRoYlGE1AjQoE',
    appId: '1:92254794352:web:12b860c32c62fc7f067ab5',
    messagingSenderId: '92254794352',
    projectId: 'nexvolt-c7eaf',
    authDomain: 'nexvolt-c7eaf.firebaseapp.com',
    storageBucket: 'nexvolt-c7eaf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-AmTqVsl4AKJfMZU4aEKdau4I9lXpmk',
    appId: '1:92254794352:android:d8d9f469f646f89d067ab5',
    messagingSenderId: '92254794352',
    projectId: 'nexvolt-c7eaf',
    storageBucket: 'nexvolt-c7eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYeHYC40a8gKDmaP8h3S8--7Ccwyp0-Oc',
    appId: '1:92254794352:ios:252f9030451c8916067ab5',
    messagingSenderId: '92254794352',
    projectId: 'nexvolt-c7eaf',
    storageBucket: 'nexvolt-c7eaf.firebasestorage.app',
    iosBundleId: 'com.example.nexvolt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYeHYC40a8gKDmaP8h3S8--7Ccwyp0-Oc',
    appId: '1:92254794352:ios:252f9030451c8916067ab5',
    messagingSenderId: '92254794352',
    projectId: 'nexvolt-c7eaf',
    storageBucket: 'nexvolt-c7eaf.firebasestorage.app',
    iosBundleId: 'com.example.nexvolt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUt0D33bGHJXbeauXkmGaRoYlGE1AjQoE',
    appId: '1:92254794352:web:5f6e82d56363d52e067ab5',
    messagingSenderId: '92254794352',
    projectId: 'nexvolt-c7eaf',
    authDomain: 'nexvolt-c7eaf.firebaseapp.com',
    storageBucket: 'nexvolt-c7eaf.firebasestorage.app',
  );
}
