// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:30592806656:web:12b860c32c62fc7f067ab5',
    messagingSenderId: '30592806656',
    projectId: 'nexvolt-493704',
    authDomain: 'nexvolt-493704.firebaseapp.com',
    storageBucket: 'nexvolt-493704.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJiqGOd8qnYzEnuUF1NjhRzeb1TKvc3I',
    appId: '1:30592806656:android:f608f5afcfdb9093144de5',
    messagingSenderId: '30592806656',
    projectId: 'nexvolt-493704',
    storageBucket: 'nexvolt-493704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVJiqGOd8qnYzEnuUF1NjhRzeb1TKvc3I',
    appId: '1:30592806656:ios:252f9030451c8916067ab5',
    messagingSenderId: '30592806656',
    projectId: 'nexvolt-493704',
    storageBucket: 'nexvolt-493704.firebasestorage.app',
    iosBundleId: 'com.example.nexvolt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVJiqGOd8qnYzEnuUF1NjhRzeb1TKvc3I',
    appId: '1:30592806656:ios:252f9030451c8916067ab5',
    messagingSenderId: '30592806656',
    projectId: 'nexvolt-493704',
    storageBucket: 'nexvolt-493704.firebasestorage.app',
    iosBundleId: 'com.example.nexvolt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVJiqGOd8qnYzEnuUF1NjhRzeb1TKvc3I',
    appId: '1:30592806656:web:5f6e82d56363d52e067ab5',
    messagingSenderId: '30592806656',
    projectId: 'nexvolt-493704',
    authDomain: 'nexvolt-493704.firebaseapp.com',
    storageBucket: 'nexvolt-493704.firebasestorage.app',
  );
}
