// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZlOKg0oyaOh73xMuqctAMiSpjTN7uRNY',
    appId: '1:19675782767:web:17aeceaa906b4cc81e779a',
    messagingSenderId: '19675782767',
    projectId: 'nexvolt-data',
    authDomain: 'nexvolt-data.firebaseapp.com',
    storageBucket: 'nexvolt-data.firebasestorage.app',
    measurementId: 'G-D8N00B8LK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQhgOg6XMmrYuSjk5VLFlOcI7nqcO3ZaQ',
    appId: '1:19675782767:android:13b52ee62d174c271e779a',
    messagingSenderId: '19675782767',
    projectId: 'nexvolt-data',
    storageBucket: 'nexvolt-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ihKbJ5xtz7g_a1PDPpz8jTxTV6EVs1U',
    appId: '1:19675782767:ios:125bca8d3dcfe5da1e779a',
    messagingSenderId: '19675782767',
    projectId: 'nexvolt-data',
    storageBucket: 'nexvolt-data.firebasestorage.app',
    iosBundleId: 'com.example.nexvolt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ihKbJ5xtz7g_a1PDPpz8jTxTV6EVs1U',
    appId: '1:19675782767:ios:125bca8d3dcfe5da1e779a',
    messagingSenderId: '19675782767',
    projectId: 'nexvolt-data',
    storageBucket: 'nexvolt-data.firebasestorage.app',
    iosBundleId: 'com.example.nexvolt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZlOKg0oyaOh73xMuqctAMiSpjTN7uRNY',
    appId: '1:19675782767:web:3150f0c4bc252b0e1e779a',
    messagingSenderId: '19675782767',
    projectId: 'nexvolt-data',
    authDomain: 'nexvolt-data.firebaseapp.com',
    storageBucket: 'nexvolt-data.firebasestorage.app',
    measurementId: 'G-PVL1X1BGRH',
  );

}